### PR TITLE
Pull request for minimap2 plugin

### PR DESCRIPTION
**Pull request by aliu104**
Hi Antonio, the minimap2 plugin is based on the qp-fastp-minimap2 plugin. Is there anything that should be changed? Could you test this plugin on qiita-rc? Thank you!

### CODE REVIEW

**Comment by antgonza** [comment]
Hi @aliu104, why did you want to rename this plugin from qp_fastp_minimap2 to qp_minimap2? Thanks.

**Comment by aliu104** [comment]
Hi @antgonza, this plugin does not use fastp and only minimap2, which is why I changed the name. The command this plugin runs is: `minimap2 -a -x sr $REF_FASTA reads_R1.fq reads_R2.fq -o output.bam`

**Comment by antgonza** [comment]
Right, I think the repo/package name should stay the same but you could add a new command with just minimap2 ... what do you think?

**Comment by aliu104** [comment]
I originally sent a pull request for this minimap2 plugin just to double check my work (i.e., to make it easier to compare what I changed between the two versions). In other words, the minimap2 plugin is supposed to be a completely separate plugin from qp-fastp-minimap2. Do you think that adding a command with just minimap2 to the existing qp-fastp-minimap2 plugin is a better idea? If so, perhaps I can double check this with Niema and make this change.

**Comment by antgonza** [comment]
I think having it in the same plugin as a new command makes sense as this will minimize plugin proliferation.

**Comment by aliu104** [comment]
Ah I see, that makes sense! I'm currently on a 2 week break before the school year starts, but I will definitely look into merging this command into the existing qp-fastp-minimap2 plugin. In the meantime, I wonder if it's possible to test the minimap2 plugin that I have in this pull request right now through qiita-rc just so I can have an idea of whether what I'm doing is working and also so that we can have a working minimap2 component of the pipeline ready for the demo as soon as possible. Let me know what you think! Thanks!

**Comment by antgonza** [comment]
Note that this PR has conflicts so I won't be able to load into qiita-rc without jumping a loop of hoops + I think we really want to test your actual command vs. something intermediary. I would suggest that you focus on creating a PR with what we want and then test that vs. doing multiple iterations of code that we will not use in the long run.

**Pull request closed without merging**
